# **************************************************************************** #
#                                                                              #
#                                                         :::      ::::::::    #
#    Makefile                                           :+:      :+:    :+:    #
#                                                     +:+ +:+         +:+      #
#    By: kokaimov <kokaimov@student.42berlin.d      +#+  +:+       +#+         #
#                                                 +#+#+#+#+#+   +#+            #
#    Created: 2023/11/14 13:31:55 by kokaimov          #+#    #+#              #
#    Updated: 2023/11/14 13:32:01 by kokaimov         ###   ########.fr        #
#                                                                              #
# **************************************************************************** #

NAME = libft.a

SRCS =	ft_isalpha.c\
		ft_isascii.c\
		ft_isalnum.c\
		ft_isdigit.c\
		ft_isprint.c\
		ft_strlen.c\
		ft_memset.c\
		ft_bzero.c\
		ft_memcpy.c\
		ft_memmove.c\
		ft_strlcpy.c\
		ft_strlcat.c\
		ft_toupper.c\
		ft_tolower.c\
		ft_strchr.c\
		ft_memchr.c\
		ft_strrchr.c\
		ft_strncmp.c\
		ft_memcmp.c\
		ft_strnstr.c\
		ft_atoi.c\
		ft_calloc.c\
		ft_strdup.c\
		ft_substr.c\
		ft_strjoin.c\
		ft_strtrim.c\
		ft_putchar_fd.c\
		ft_putstr_fd.c\
		ft_putendl_fd.c\
		ft_putnbr_fd.c\
		ft_split.c\
		ft_itoa.c\
		ft_strmapi.c\
		ft_striteri.c


BSRCS =	ft_lstclear.c\
		ft_lstnew.c\
		ft_lstadd_back.c\
		ft_lstadd_front.c\
		ft_lstsize.c\
		ft_lstlast.c\
		ft_lstdelone.c\
		ft_lstiter.c\
		ft_lstmap.c

OBJ = $(SRCS:.c=.o)

BOBJ = $(BSRCS:.c=.o)

CFLAGS = -Wall -Wextra -Werror

%.o: %.c
	@ cc $(CFLAGS) -c $< -o $@

all: $(NAME)

$(NAME): $(OBJ) $(BOBJ)
	@ ar rc $(NAME) $(OBJ) $(BOBJ)
	@ ranlib $(NAME)

mandatory: $(OBJ)
	@ ar rc $(NAME) $(OBJ)

bonus: $(BOBJ)
	@ ar rc $(NAME) $(BOBJ)

clean:
	rm -f $(OBJ) $(BOBJ)

fclean: clean
	rm -f $(NAME)

re: fclean all

.PHONY: all clean fclean re